### ISSUE TITLE
Facility to ingest and process rnaseqc2 metrics file

### ISSUE THREAD

**Issue by Rohit-Satyam** [smped/ngsReports#39]
This is a request for enhancement. [Rnaseqc2](https://github.com/getzlab/rnaseqc) provides useful and more elaborate stats that I believe are instrumental to check the library health. It would be wonderful, if you could inculcate the capability to read and plot the stats obtained from it's file. The architecture of the metrics file produced is simple. If I got time, I will write and share few functions that can be used.

**Comment by smped** [comment]
Thanks @Rohit-Satyam . I'm in the middle of a fairly large upgrade to better work with `fastp` json files as that's become our tool of choice, so I'll add this one to the list. I haven't looked at an output file yet, but if they're simple like many other tools, it'll be easy. If they're complex & modular like FastQC & Fastp, it'll probably take a bit longer. 

Happy to look at any pull requests too

**Comment by smped** [comment]
Hi @Rohit-Satyam 

There's been some discussion amongst developers about restricting updates to packages after release to bug fixes, so I've held off on this. I've just added the capacity though so it's now available here & will be incorporated into the next Bioconductor release.

And thanks for the heads up about `rnaseqc` too. Looks like a really useful tool!
