### ISSUE TITLE
Adjust check for file existence in zipped FastQC output in function `.getFqcLines() `

### ISSUE THREAD

**Issue by baerlachlan** [smped/ngsReports#45]
Hey Stevie. Have run into a niche problem when using `writeHtmlReport()` on zipped FastQC outputs. If the archive was renamed after its creation, the check uses the new name to look inside the archive contents, which actually contains a directory with the original name. An error is triggered from the `.getFqcLines() ` function at the check `stopifnot(fl %in% allFiles)`. The problem specifically occurs because of `fl <- file.path(gsub(".zip$", "", basename(path)), "fastqc_data.txt")`, which uses the basename of the zip file, and is different to the directory to be extracted. A slight reordering/adjustment to the current code might be a solution. Here's a starting point:

```
allFiles <- unzip(path, list = TRUE)$Name
fl <- file.path(gsub(".zip$", "", basename(allFiles[1])), "fastqc_data.txt")
stopifnot(fl %in% allFiles)
```

Cheers

**Comment by smped** [comment]
Great pickup. Thanks @baerlachlan!

Fixed in 9894100
